# Theme
minimal_mistakes_skin: "default"

# Site Settings
locale: "en-US"
title: "Peter Obami"
title_separator: "-"
name: "Peter Obami"
description: "Innovator • Mentor • Leadership Guide • Personal Growth Coach"
url: "https://peterobami.github.io"
baseurl: ""

# Author
author:
  name: "Peter Obami"
  bio: "Helping people unlock clarity, confidence, and direction."
  location: "United Kingdom"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-square-envelope"
      url: "mailto:hello@peterobami.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/peterobami"

# Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/peterobami"
  since: "2026"

# Search
search: true
search_provider: lunr

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Reading
include:
  - _pages

exclude:
  - vendor
  - node_modules
  - tmp
  - /docs
  - /test

# Markdown
markdown: kramdown
highlighter: rouge

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Output
permalink: /:categories/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
